main: ${mainClass}
name: ${name}
version: ${version}
api-version: 1.19
author: ds58
depend: [ WorldGuard, ProtocolLib ]
commands:
  request:
    description: Request a video to be added to a theater queue
    aliases: [ rq ]
  forceskip:
    description: Force skip a video
  volume:
    description: Set the volume for videos
